[tool.pylint.messages_control]

disable = [
    "attribute-defined-outside-init",
    "invalid-name",
    "missing-docstring",
    "missing-function-docstring",
    "protected-access",
    "too-few-public-methods",
    "format",
    "fixme",
    "cyclic-import",
    "import-error",
    "no-value-for-parameter",
    "wrong-import-order",
    "duplicate-code",
    "consider-using-with",
    "missing-timeout"
]