{
 "title": "Evidently Dashboards",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Drift Score",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT drift_score FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Dataset Drift",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT dataset_drift FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Missing Values",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT missing_values FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Correlation",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT correlation FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Quantile - Age",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT quantile FROM dummy_metrics LIMIT 50 "
    }
   ]
  }
 ]
}